caas/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('portal/', include('portal.urls')),
]

portal/urls.py
from django.urls import path, include, re_path
from . import views

app_name = 'portal'
urlpatterns = [
	path('', views.landing, name = 'landing'),
	path('login_system/', views.login_system, name = 'login_system'),
	path('register/', views.register, name = 'register'),
	path('logout_system/', views.logout_system, name = 'logout_system'),
	path('home/', views.home, name = 'home'),

	path('instances/', views.instances, name = 'instances'),
	path('instances/<action>/<instance_id>/', views.instance_action, name = 'instance_action'),

	path('volumes/', views.volumes, name = 'volumes'),
	path('volumes/<action>/<volume_id>/', views.volume_action, name = 'volume_action'),

	path('images/', views.images, name = 'images'),
	path('images/<action>/<image_id>/', views.image_action, name = 'image_action'),

	path('keypairs/', views.keypairs, name = 'keypairs'),
	path('keypairs/<action>/<keypair_name>/', views.keypair_action, name = 'keypair_action'),

	path('networks/', views.networks, name = 'networks'),
	path('networks/<action>/<network_id>/', views.network_action, name = 'network_action'),

	path('flavors/', views.flavors, name = 'flavors'),
	path('flavors/<action>/<flavor_id>/', views.flavor_action, name = 'flavor_action'),

	path('stacks/', views.stacks, name = 'stacks'),
	path('create_stack/', views.create_stack, name = 'create_stack'),
	path('create_stack/exec', views.stack_exec, name = 'stack_exec'),
	path('stacks/detail/<stack_name>/<stack_id>/', views.stack_detail, name = 'stack_detail'),
	path('stacks/<action>/<stack_name>/<stack_id>/', views.stack_action, name = 'stack_action'),
	# Management site URLs
	path('manage/instances/', views.mgr_instances, name = 'mgr_instances'),
	path('manage/instances/<action>/<instance_id>/', views.mgr_instance_action, name = 'mgr_instance_action'),


	path('manage/', views.mgr_hypervisors, name = 'mgr_home'),
	path('manage/hypervisors/', views.mgr_hypervisors, name = 'mgr_hypervisors'),

	path('manage/users/', views.mgr_users, name = 'mgr_users'),
	path('manage/users/<action>/<user_id>/', views.mgr_user_action, name = 'mgr_user_action'),
	path('manage/users/create/', views.mgr_user_create, name = 'mgr_user_create'),

	path('manage/projects/', views.mgr_projects, name = 'mgr_projects'),
	path('manage/projects/<action>/<project_id>/', views.mgr_project_action, name = 'mgr_project_action'),
	path('manage/projects/create/', views.mgr_project_create, name = 'mgr_project_create'),

	path('manage/roles/', views.mgr_roles, name = 'mgr_roles'),
	path('manage/roles/<action>/<role_id>/', views.mgr_role_action, name = 'mgr_role_action'),
	path('manage/roles/create/', views.mgr_role_create, name = 'mgr_role_create'),

]

portal/models.py
from django.db import models





# Create your models here.

portal/views/authentication.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth import logout, login

import json, requests
import os
#----------------------------------------------------------------------------------------------------------------
# READ IP
module_dir = os.path.dirname(__file__)
with open(os.path.join(module_dir, 'apis_call_ip.txt')) as f:
	IP = f.read().split('\n')
#----------------------------------------------------------------------------------------------------------------
def login_system(request):
	response = render(request, 'portal/login.html')
	payload = {
    "auth": {
        	"identity": {
            	"methods": [
	                "password"
            	],
            	"password": {
                	"user": {
                    	"name": request.POST.get('username',False),
                    	"domain": {
                        	"name": request.POST.get('domainname',False),
                    	},
                    	"password": request.POST.get('password',False),
                	}
            	}
        	},
        	"scope": {
            	"project": {
                	"name": request.POST.get('projectname',False),
					"domain": {
						"name": request.POST.get('domainname',False),
					},
            	}
        	}
    	}
	}
	url = 'http://' + IP[0] + ':5000/v3/auth/tokens'
	api_res = requests.post(url, data=json.dumps(payload))

	if api_res.status_code == 401:
		return render(request,'portal/login.html',{'login_status': "401: Unauthorized - Credentials are not correct",})
	if api_res.status_code == 201:
		
		response = HttpResponseRedirect(reverse('portal:home'))
		request.session['user_name'] = api_res.json().get('token',{}).get('user',{}).get('name',{})
		request.session['user_id'] = api_res.json().get('token',{}).get('user',{}).get('id',{})
		request.session['domain_name'] = api_res.json().get('token',{}).get('user',{}).get('domain',{}).get('name',{})
		request.session['domain_id'] = api_res.json().get('token',{}).get('user',{}).get('domain',{}).get('id',{})
		request.session['X_Auth_Token'] = api_res.headers.get('X-Subject-Token')
		request.session['project_name'] = api_res.json().get('token',{}).get('project',{}).get('name',{})
		request.session['project_id'] = api_res.json().get('token',{}).get('project',{}).get('id',{})
		request.session['token_issued'] = api_res.json().get('token',{}).get('issued_at',{})
		request.session['token_expires'] = api_res.json().get('token',{}).get('expires_at',{})
		request.session['roles'] = api_res.json().get('token',{}).get('roles',{})
		#request.session['ip'] = IP check admin trong home template se goi va lay ip[1] <- username cua admin he thong
		return response

	return response

def logout_system(request):
	logout(request)
	return render(request, 'portal/landing.html')

def check_auth(request):
	url = 'http://' + IP[0] + ':8774/v2.1/servers'
	api_res = requests.get(url, headers={"X-Auth-Token":request.session.get('X_Auth_Token', 'Not logged in')} )
	if api_res.status_code == 200:
		return True
	else:
		return False

def check_admin(request):
	# neu ton tai role la admin thi se vao dc trang admin
	roles = request.session.get('roles','Not logged in')
	for role in roles:
		for key, value in role.items():
			if key == 'name' and value =='admin':
				return True
	else:
		return False

portal/views/create_stack.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

import json, requests

from .authentication import *

def create_stack(request):
	if check_auth(request) == False:
	    return render(request,'portal/login.html',{'login_status': "401: Session Expired or you are not logged in",})
	
	flavor_detail_url = 'http://'+ IP[0] + ':8774/v2.1/flavors/detail'
	flavor_detail_res = requests.get(flavor_detail_url, headers={"X-Auth-Token":request.session.get('X_Auth_Token', 'Not logged in')} )
	image_detail_url = 'http://'+ IP[0] + ':9292/v2/images'
	image_detail_res = requests.get(image_detail_url, headers={"X-Auth-Token":request.session.get('X_Auth_Token', 'Not logged in')} )
	keypair_detail_url = 'http://'+ IP[0] + ':8774/v2.1/os-keypairs'
	keypair_detail_res = requests.get(keypair_detail_url, headers={"X-Auth-Token":request.session.get('X_Auth_Token', 'Not logged in')} )
	network_detail_url = 'http://'+ IP[0] + ':9696/v2.0/networks'
	network_detail_res = requests.get(network_detail_url, headers={"X-Auth-Token":request.session.get('X_Auth_Token', 'Not logged in')} )


	context = {
	    'flavor_list': flavor_detail_res.json(),
	    'image_list' : image_detail_res.json(),
	    'keypair_list' : keypair_detail_res.json(),
	    'network_list' :network_detail_res.json()
	}


	return render(request, 'portal/create_stack.html', context)
def stack_exec(request):
	stack_exec_url = 'http://'+ IP[0] + ':8004/v1/' + request.session.get('project_id','Not logged in') + '/stacks'
	
	if request.POST.get('keypair', False) == 'true':
		disable_rollback = False
	else: 
		disable_rollback = True

	if request.POST.get('stack', False) == 'galeradb':
		payload = {
		    "disable_rollback": disable_rollback,
		    "parameters": {
		        "key_name": request.POST.get('keypair', False),
		        "image" : request.POST.get('image', False),
		        "flavor" : request.POST.get('flavor', False),
		        "network" : request.POST.get('network', False),
		        "db_password" : request.POST.get('db_password', False)
		    },
		    "template_url": "https://s3-ap-northeast-1.amazonaws.com/vusonhust/heat-template/galera.yml",
		    "stack_name": request.POST.get('stack_name', False),
		    "timeout_mins": request.POST.get('stack_timeout', False)
		}
		stack_add_exec = requests.post(stack_exec_url, data=json.dumps(payload), headers={"X-Auth-Token":request.session.get('X_Auth_Token', 'Not logged in')} )

	if request.POST.get('stack', False) == 'HAProxy':
		payload = {
		    "disable_rollback": disable_rollback,
		    "parameters": {
		        "key_name": request.POST.get('keypair', False),
		        "image" : request.POST.get('image', False),
		        "flavor" : request.POST.get('flavor', False),
		        "network" : request.POST.get('network', False)
		    },
		    "template_url": "https://s3-ap-northeast-1.amazonaws.com/vusonhust/heat-template/HAProxyLB.yaml",
		    "stack_name": request.POST.get('stack_name', False),
		    "timeout_mins": request.POST.get('stack_timeout', False)
		}
		stack_add_exec = requests.post(stack_exec_url, data=json.dumps(payload), headers={"X-Auth-Token":request.session.get('X_Auth_Token', 'Not logged in')} )

	if request.POST.get('stack', False) == 'GlusterFS':
		payload = {
		    "disable_rollback": disable_rollback,
		    "parameters": {
		        "key_name": request.POST.get('keypair', False),
		        "image" : request.POST.get('image', False),
		        "flavor" : request.POST.get('flavor', False),
		        "network" : request.POST.get('network', False)
		    },
		    "template_url": "https://s3-ap-northeast-1.amazonaws.com/vusonhust/heat-template/GlusterFS4_centos_distributed.yaml",
		    "stack_name": request.POST.get('stack_name', False),
		    "timeout_mins": request.POST.get('stack_timeout', False)
		}
		stack_add_exec = requests.post(stack_exec_url, data=json.dumps(payload), headers={"X-Auth-Token":request.session.get('X_Auth_Token', 'Not logged in')} )


	if request.POST.get('stack', False) == 'WP':
		payload = {
		    "disable_rollback": disable_rollback,
		    "parameters": {
		        "key_name": request.POST.get('keypair', False),
		        "image" : request.POST.get('image', False),
		        "flavor" : request.POST.get('flavor', False),
		        "network" : request.POST.get('network', False),
		        "db_name" : request.POST.get('db_name', False),
		        "db_password" : request.POST.get('db_password', False)
		    },
		    "template_url": "https://s3-ap-northeast-1.amazonaws.com/vusonhust/heat-template/wordpress.yml",
		    "stack_name": request.POST.get('stack_name', False),
		    "timeout_mins": request.POST.get('stack_timeout', False)
		}
		stack_add_exec = requests.post(stack_exec_url, data=json.dumps(payload), headers={"X-Auth-Token":request.session.get('X_Auth_Token', 'Not logged in')} )


	return HttpResponseRedirect(reverse('portal:stacks'))

portal/views/flavors.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth import logout, login

import json, requests
import os

from .authentication import *

def flavors(request):
    if check_auth(request) == False:
        return render(request,'portal/login.html',{'login_status': "401: Session Expired or you are not logged in",})
    flavor_detail_url = 'http://'+ IP[0] + ':8774/v2.1/flavors/detail'
    flavor_detail_res = requests.get(flavor_detail_url, headers={"X-Auth-Token":request.session.get('X_Auth_Token', 'Not logged in')} )
    if flavor_detail_res.status_code == 200:
        context = {
            'user_name' : request.session.get('user_name','Not logged in'),
            'data': flavor_detail_res.json()
        }
        return render(request, 'portal/flavors.html',context)
    return render(request, 'portal/flavors.html')

def flavor_action(request, action, flavor_id):
    if check_auth(request) == False:
        return render(request,'portal/login.html',{'login_status': "401: Session Expired or you are not logged in",})
    action_url = 'http://'+ IP[0] + ':8774/v2.1/flavors/'+ flavor_id
    action_exec = requests.delete(action_url, headers={"X-Auth-Token":request.session.get('X_Auth_Token', 'Not logged in')} )

    return HttpResponseRedirect(reverse('portal:flavors'))

portal/views/home.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

import json, requests

from .authentication import *

def home(request):
	if check_auth(request) == False:
		return render(request,'portal/login.html',{'login_status': "401: Session Expired or you are not logged in",})

	is_admin = False
	if check_admin(request) == True:
		is_admin = True
	compute_quotas_url = 'http://' + IP[0] + ':8774/v2.1/os-quota-sets/' + request.session.get('project_id','Not logged in') + '/detail'
	compute_quotas_res = requests.get(compute_quotas_url, headers={"X-Auth-Token":request.session.get('X_Auth_Token', 'Not logged in')} )

	volume_quotas_url = 'http://' + IP[0] + ':8776/v3/' + request.session.get('project_id','Not logged in') + '/os-quota-sets/' + request.session.get('project_id','Not logged in') + '?usage=True'
	volume_quotas_res = requests.get(volume_quotas_url, headers={"X-Auth-Token":request.session.get('X_Auth_Token', 'Not logged in')} )

	network_quotas_url = 'http://' + IP[0] + ':9696/v2.0/quotas/' + request.session.get('project_id','Not logged in') + '/details.json'
	network_quotas_res = requests.get(network_quotas_url, headers={"X-Auth-Token":request.session.get('X_Auth_Token', 'Not logged in')} )


	return render(request, 'portal/home.html',{
		'user_name' : request.session.get('user_name','Not logged in'),
		'user_id' : request.session.get('user_id','Not logged in'),
		'domain_name' : request.session.get('domain_name','Not logged in'),
		'domain_id' : request.session.get('domain_id','Not logged in'),
		'X_Auth_Token' : request.session.get('X_Auth_Token', 'Not logged in'),
		'roles': request.session.get('roles', 'Not logged in'),
		'project_name' : request.session.get('project_name','Not logged in'),
		'project_id' : request.session.get('project_id','Not logged in'),
		'token_issued' : request.session.get('token_issued','Not logged in'),
		'token_expires' : request.session.get('token_expires','Not logged in'),
		'compute_quotas' : compute_quotas_res.json(),
		'volume_quotas' : volume_quotas_res.json(),
		'network_quotas' : network_quotas_res.json(),
		'is_admin' : is_admin,
		})

portal/views/images.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth import logout, login

import json, requests
import os

from .authentication import *

def images(request):
    if check_auth(request) == False:
        return render(request,'portal/login.html',{'login_status': "401: Session Expired or you are not logged in",})
    image_detail_url = 'http://'+ IP[0] + ':9292/v2/images'
    image_detail_res = requests.get(image_detail_url, headers={"X-Auth-Token":request.session.get('X_Auth_Token', 'Not logged in')} )

    #Pass Project owner to context
    project_detail_url = 'http://' + IP[0] + ':5000/v3/projects'
    project_detail_res = requests.get(project_detail_url, headers={"X-Auth-Token":request.session.get('X_Auth_Token', 'Not logged in')})

    if image_detail_res.status_code == 200 and project_detail_res.status_code == 200:
        context = {
            'user_name' : request.session.get('user_name','Not logged in'),
            'data': image_detail_res.json(),
            'project_detail': project_detail_res.json()
        }
        return render(request, 'portal/images.html',context)
    elif image_detail_res.status_code == 200 and project_detail_res.status_code == 403:
        context = {
            'user_name' : request.session.get('user_name','Not logged in'),
            'data': image_detail_res.json(),
            'project_detail': '403'
        }
        return render(request, 'portal/images.html',context)

    return render(request, 'portal/images.html')

def image_action(request, action, image_id):
    if check_auth(request) == False:
        return render(request,'portal/login.html',{'login_status': "401: Session Expired or you are not logged in",})
    action_url = 'http://'+ IP[0] + ':9292/v2/images/' + image_id
    action_exec = requests.delete(action_url, headers={"X-Auth-Token":request.session.get('X_Auth_Token', 'Not logged in')} )

    return HttpResponseRedirect(reverse('portal:images'))

portal/views/landing.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth import logout, login

import json, requests
import os

def landing(request):
	return render(request, 'portal/landing.html')

portal/templates/portal/mgr_projects.html
{% load static %}
{% load portal_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>CaaS - HPCC</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.12/css/all.css" integrity="sha384-G0fIWCsCzJIMAVNQPfjH08cyYaUtMwjJwqiRKxxE/rx96Uroj1BtIQ6MLJuheaO9" crossorigin="anonymous">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons">
  <link rel="stylesheet" href="https://unpkg.com/bootstrap-material-design@4.1.1/dist/css/bootstrap-material-design.min.css" integrity="sha384-wXznGJNEXNG1NFsbm0ugrLFMQPWswR3lds2VeinahP8N0zJw9VWSopbjv2x7WCvX" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://unpkg.com/popper.js@1.12.6/dist/umd/popper.js" integrity="sha384-fA23ZRQ3G/J53mElWqVJEGJzU0sTs+SvzG8fXVWP+kJQ1lwFAOkcUOysnlKJC33U" crossorigin="anonymous"></script>
  <script src="https://unpkg.com/bootstrap-material-design@4.1.1/dist/js/bootstrap-material-design.js" integrity="sha384-CauSuKpEqAFajSpkdjv3z9t8E7RlpJ1UP0lKM/+NdtSarroVKu069AlsRPKkFBz9" crossorigin="anonymous"></script>

  <style>
  td {
    white-space: normal !important;
    word-wrap: break-word;
    vertical-align: middle !important;
  }
  table {
    table-layout: fixed;
  }

  </style>
</head>


<body>


<nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'portal:mgr_home' %}">CaaS - System Management</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mr-auto nav-tabs">

        <li class="nav-item">
          <a class="nav-link" href="{% url 'portal:mgr_hypervisors' %}">Hypervisors</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'portal:mgr_users' %}">Users</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'portal:mgr_projects' %}">Projects</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'portal:mgr_roles' %}">Roles</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'portal:mgr_instances' %}">Instances</a>
        </li>
      </ul>
      <span class="navbar-text">
        <button type="button" class="btn btn-raised btn-secondary" data-toggle="modal" data-target="#addprojectmodal">
          <i class="fas fa-plus"></i> Create Project
        </button>
        <a href="{% url 'portal:home' %}"><button type="button" class="btn btn-raised btn-secondary">HOME</button></a>
        <button type="button" class="btn btn-raised btn-secondary"><a href="{% url 'portal:logout_system' %}"><i class="fas fa-sign-out-alt"></i> Logout</a></button>
      </span>
    </div>
</nav>


<div class="container-fluid">
      <h2>Welcome {{ user_name }} | Projects </h2>
      <table class="table table-bordered table-hover">
        <thead class="thead-dark">
          <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Project ID</th>
            <th>Domain name</th>
            <th>Enabled</th>
            <th style="width: 8%">Actions</th>

          </tr>
        </thead>

        <tbody>
          {% for project in system_project_list.projects %}
            <tr>
            <td>{{ project.name }}</td>
            <td>{{ project.description }}</td>
            <td>{{ project.id }}</td>
            <td>
              {% for domain in system_domain_list.domains %}
                {% if project.domain_id == domain.id %} {{domain.name}}
                {% endif %}
              {% endfor %}
            </td>
            <td>
              {% if project.enabled == True %} Yes
              {% elif project.enabled == False %} No
              {% endif %}
            </td>



            <td>
            <div class="btn-group dropdown">
                <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Choose
                </button>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton" >
                  {% if project.enabled == True %}
                  <a class="dropdown-item" href="{% url 'portal:mgr_project_action' 'disable' project.id %}">Disable Project</a>
                  {% elif project.enabled == False %}
                  <a class="dropdown-item" href="{% url 'portal:mgr_project_action' 'enable' project.id %}">Enable Project</a>
                  {% endif %}

                  <a class="dropdown-item" href="{% url 'portal:mgr_project_action' 'delete' project.id %}" style="color:red">DELETE PROJECT</a>
                </div>

            </div>
            </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
</div>


<!-- Modal add project-->
<div class="modal fade" id="addprojectmodal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add new project:</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="{% url 'portal:mgr_project_create' %}" method="post" id="admin_add_project">
          {% csrf_token %}
          <div class="form-group">
            <label for="user_name">Project name</label>
            <input type="text" class="form-control" id="project_name" name="project_name" placeholder="Enter Project name" required>
          </div>
          <div class="form-group">
            <label for="description">Description</label>
            <input type="text" class="form-control" id="description" name="description" placeholder="Enter description">
          </div>
          <div class="form-group">
            <label for="domain_id">Domain ID</label>
            <input type="text" class="form-control" id="domain_id" name="domain_id" value="{{domain_id}}" placeholder="{{domain_id}}" readonly>
          </div>
          <div class="form-check">
            <input type="checkbox" class="form-check-input" id="is_domain" name="is_domain" value= "true">
            <label class="form-check-label" for="exampleCheck1" >Is Domain (to create a project that also acts as a domain)</label>
          </div>
          <div class="form-check">
            <input type="checkbox" class="form-check-input" id="project_enable" name="enable" value= "true">
            <label class="form-check-label" for="exampleCheck1" >Enable Project</label>
          </div>
          <button type="submit" form="admin_add_project" class="btn btn-primary">Submit</button>
        </form>
      </div>
    </div>
  </div>
</div>
<!--
<footer class="container-fluid text-left">
  <div>[CONFIDENTAL] Vu Anh Son - HEDSPI 8 - Thesis - Cluster as a Service v0.2</div>
</footer>
-->
</body>
</html>